[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[dependencies]
ahash = "0.8.12"
clap = "4.5.48"
cmp = "1.0.0"
error-iter = "0.4.1"
log = "0.4.28"
pixels = "0.15.0"
rand = "0.9.2"
wgpu = "26.0.1"
winit = "0.30.12"
